food_delivery/urls.py
from app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api import views as api_views
from rest_framework.authtoken import views as drf_views

router = DefaultRouter()
router.register('users', api_views.UserApiView, basename='users')
router.register('categories', api_views.ProductCategoryApiView, basename='categories')
router.register('products', api_views.ProductApiView, basename='products')

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.MainView.as_view()),
                  path('about-us/', views.AboutUsView.as_view()),
                  path('tech/room-list/', views.RoomListView.as_view()),
                  path('tech-support/<int:room_name_id>/', views.TechSupportView.as_view()),

                  path('api/', include(router.urls)),
                  path('api/categories/', api_views.ProductCategoryApiView.as_view()),
                  path('api-token-auth/', drf_views.obtain_auth_token),

                  path('signup/', views.SignUpView.as_view(), name='signup'),
                  path('login/', LoginView.as_view(template_name="login.html")),
                  path('logout/', LogoutView.as_view()),
                  path('<slug:slug>/profile/', views.UserPageView.as_view(), name='user_profile'),
                  path('<slug:slug>/profile/update/', views.UpdateUserPersonalInfoView.as_view()),
                  path('update-card/', views.UserCardView.as_view(), name='update_card'),
                  path('<slug:slug>/profile/order-history/', views.OrderHistoryView.as_view()),

                  path('category/', views.CategoryView.as_view()),
                  path('category/<slug:slug>/', views.ProductView.as_view(), name='product_list'),
                  path('category/<slug:category>/<slug:slug>/', views.ProductInfoView.as_view(), name='product_info'),

                  path('add_to_cart/', views.AddToCartView.as_view(), name='add_to_cart'),
                  path('del_element_from_cart/', views.DeleteElementFromCartView.as_view(),
                       name='del_element_from_cart'),
                  path('del_all_elements_from_cart/', views.DeleteAllElementsFromCartView.as_view(),
                       name='del_all_elements_from_cart'),
                  path('cart/', views.CartView.as_view()),

                  path('checkout/', views.CheckoutView.as_view(), name='checkout'),
                  path('create-charge/', views.ChargeView.as_view(), name='create-charge'),
                  path('success/', views.SuccessView.as_view(), name='success'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

app/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.template.defaultfilters import slugify


def user_upload_to(obj, file_name):
    return f"media/{obj.username}/{file_name}"


def product_upload_to(obj, file_name):
    return f"static/img/{obj.category}/{file_name}"


class UserProfile(AbstractUser):
    address = models.CharField(max_length=150, null=True, blank=True)
    phone_number = models.CharField(max_length=10)
    avatar = models.ImageField(upload_to=user_upload_to, null=True, blank=True)
    bonus_coins = models.FloatField(default=0)
    order_history = models.ManyToManyField("app.Cart")
    slug = models.SlugField()
    stripe_customer_id = models.CharField(max_length=250, null=True, blank=True)
    default_card = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.username)
        super(get_user_model(), self).save(*args, **kwargs)


class SameField(models.Model):
    main_image = models.ImageField(upload_to=product_upload_to, null=True, blank=True)
    slug = models.SlugField(null=True)

    class Meta:
        abstract = True


class ProductCategory(SameField):
    category = models.CharField(max_length=50)

    def __str__(self):
        return self.category

    def save(self, *args, **kwargs):
        self.slug = slugify(self.category)
        super(ProductCategory, self).save(*args, **kwargs)


class Product(SameField):
    title = models.CharField(max_length=50)
    compound = models.CharField(max_length=150)
    description = models.CharField(max_length=200)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    price = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(250)])
    available = models.BooleanField(default=True)
    rating = models.IntegerField(default=0)
    added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)


class Image(models.Model):
    product = models.ForeignKey('app.Product', on_delete=models.CASCADE)
    images = models.ImageField(upload_to='static/img/images/', null=True, blank=True)

    def __str__(self):
        return self.product.title


class CartItem(models.Model):
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.item} || {self.quantity}'

    def get_total_price(self):
        return self.quantity * self.item.price


class Cart(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True, blank=True)
    items = models.ManyToManyField(CartItem)
    ordered_date = models.DateTimeField(auto_now_add=True)
    ordered = models.BooleanField(default=False)
    session_key = models.CharField(max_length=255, editable=False)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    address = models.CharField(max_length=150)
    phone_number = models.IntegerField(null=True, blank=True)
    description = models.CharField(max_length=255, null=True, blank=True)
    payment_choice = models.CharField(max_length=40)

    def __str__(self):
        return f'{self.user} || {self.ordered}'

    def get_total(self):
        return list(map(lambda e, i: e + i.get_total_price(), [0], self.items.all()))[0]

    def items_counter(self):  # todo  для глбального отображение кол-ва предметов в корзине, нужно ли?
        total = 0
        for item in self.items.all():
            total += item.quantity
        return list(map(lambda k, i: k + i.quantity, [0], self.items.all()))[0]


class Room(models.Model):
    room_name = models.CharField(max_length=255)

    def __str__(self):
        return self.room_name


class Messages(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    from_user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    message = models.TextField()

    def __str__(self):
        return self.from_user.username

app/templates/all-category-page.html
{% extends "base.html" %}
{% load bootstrap_icons %}
{% load thumbnail %}


{% block css %}
    <style>
        .btn-lg {
            width: 80%;
        }
    </style>
{% endblock %}

{% block page %}
    <div class="container">
        <div class="row">
            <div class="col-md-12"><br>
            <!--Block Popular Items-->
                <div class="card shadow">
                    <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-10"> <br>
                        <h1 class="text-center">Most popular</h1>
                        <br><hr><br>
                            <div class="row">
                                {% for item in items_rating %}
                                    <div class="col-md-3" >
                                        <div>
                                            <div class="text-center" >
                                                <a href="/category/{{ item.category.slug }}/{{ item.slug }}/" style="text-decoration: none; color: #F5EEC2" >
                                                    {% thumbnail item.main_image "200x200" crop="center" as im %}
                                                        <p><img src="{{ im.url }}" style="border-radius: 5px" alt="category_img"></p>
                                                    {% endthumbnail %}
                                                    <p>₴ {{ item.price }}</p>
                                                    <p><button  class="btn-lg btn-palegreen">{{ item.title }}</button></p>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div> <br>
                        </div>
                        <div class="col-md-1"></div>
                    </div>
                </div>
            <!--END Block Popular Items-->
            <br>
            <!--Block Categories-->
                <div class=" card shadow">
                    <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-10"><br>
                            <h1 class="text-center">Categories</h1>
                            <br><hr><br>
                            <div class="row">
                                {% for category in context_category %}
                                    <div class="col-md-3">
                                        <div>
                                            <div class="text-center">
                                                <a href="/category/{{ category.slug }}">
                                                {% thumbnail category.main_image "200x200" crop="center" as im %}
                                                    <p><img src="{{ im.url }}" style="border-radius: 5px" alt="category_img"></p>
                                                {% endthumbnail %}
                                                <p><button  class="btn-lg btn-palegreen">{{ category.category }}</button></p>
                                                </a>
                                            </div><br>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="col-md-1"></div>
                    </div>
                </div>
            <!--END Block Categories-->
            </div>
        </div>
    </div>
{% endblock %}

app/templates/base.html
{% load static %}
{% load thumbnail %}
{% load bootstrap_icons %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gros.Delivery</title>

    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/bootstrap.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block css %} {% endblock css %}
</head>

<body style="background-color: #efeff5 ;">
{% csrf_token %}
<!--NavBar-->
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #39395f;">
    <div class="container-fluid">
        <a class="navbar-brand" href="/" style="color: #a9c25d">Gros.Delivery</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                <!--Category-->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" style="color: #f5eec2">Categories
                        of products</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for contex in context_category %}
                            <a class="dropdown-item" href="/category/{{ contex.slug }}/">{{ contex.category }}</a>
                        {% endfor %}
                    </ul>
                </li>
            </ul>

            <form class="d-flex" enctype="multipart/form-data">
                <div class="d-flex align-items-center">

                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                        <!--User-->
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown" style="position:relative; right:30px;">

                                <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    {% if user.avatar %}
                                        {% thumbnail user.avatar "30x30" crop="center" as im %}
                                            <img src="{{ im.url }}" class="rounded-circle" alt="avatar">
                                        {% endthumbnail %}
                                    {% else %}
                                        <img style="height: 30px; width: 30px" src="{% static 'img/no_img.png' %}">
                                    {% endif %}
                                </a>

                                <ul class="dropdown-menu" style="background-color: #F5EEC2; border-color: #0a0a0a;"
                                    aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item btn btn-success" href="/{{ user.slug }}/profile/">Profile</a>
                                    </li>
                                    <li><a class="dropdown-item" href="/{{ user.slug }}/profile/update/">Settings</a>
                                    </li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="/logout/">Logout</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <a class="btn btn-palegreen" style="position:relative; right:40px;" href="/login/">
                                Login </a>
                            <a class="btn btn-palegreen" style="position:relative; right:30px;"
                               href="/signup/">SignUp </a>
                        {% endif %}
                        <!--Cart-->
                        {% if context_cart_exist %}
                            <a href="/cart/"
                               style="position:relative; right:20px; color: #f5eec2">{% bs_icon 'bag-check-fill' size='2em' %}</a>
                        {% else %}
                            <a href="/cart/"
                               style="position:relative; right:20px; color: #f5eec2">{% bs_icon 'bag' size='2em' %}</a>
                        {% endif %}

                        <!--About Us-->
                        <li class="nav-item">
                            <a class="nav-link" href="/about-us/" style="color: #f5eec2">About us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/admin/" style="color: #f5eec2">admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/tech-support/" style="color: #f5eec2">Tech Support</a>
                        </li>
                    </ul>
                </div>
            </form>
        </div>
    </div>
</nav>
<!--EndNavBar-->

<!--Message-->
{% if messages %}
    {% for message in messages %}
        <div class="container-fluid p-0">
            <div class="alert {{ message.tags }}" role="alert">
                <span style="font-size: 20px">{{ message }}</span>
            </div>
        </div>
    {% endfor %}
{% endif %}

<script>
    alertify.set('notifier', 'position', 'bottom-right');
    {% for message in messages %}
        alertify.error('{{ message }}');
    {% endfor %}
</script>
<!--EndMessage-->
{% block page %} {% endblock page %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
<script src="{% static 'js/base.js' %}"></script>

{% block js %}

{% endblock %}
</body>
</html>

app/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}



{% block js %}
    <script src="{% static 'js/checkout.js' %}"></script>
{% endblock js %}

{% block page %}
    <!--Page-->
    <div class="row"> {% csrf_token %}
        <div class="col-md-2"></div>
        <div class="col-md-5"><br>
            <!--Card-->
            <div class="card shadow">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-10">
                            <!--Personal info-->
                            <div class="row">
                                <div class="col-md-12">
                                    <p class="text-center" style="font-size: 25px;">Checkout</p>
                                    <hr>
                                    <form method="post">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6">
                                                <p>First Name</p>
                                                <p>{{ form.first_name|add_class:'form-control'|default_if_none:'' }}</p>
                                                <p>Phone Number</p>
                                                <p>{{ form.phone_number|add_class:'form-control'|default_if_none:'' }}</p>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Last Name</p>
                                                <p>{{ form.last_name|add_class:'form-control'|default_if_none:'' }}</p>
                                                <p>Address</p>
                                                <p>{{ form.address|add_class:'form-control'|default_if_none:'' }}</p>
                                            </div>
                                        </div>
                                        <hr>
                                        <p>Description</p>
                                        <p>{% render_field form.description class='form-control' placeholder='Description' %}</p>

                                        <!--Payment Choices-->
                                        {{ form.payment_choice }}
                                        <br>
                                        <div class="d-grid gap-2">
                                            <!--Cash-->
                                            <button type="submit" id="payment-cash" hidden class="btn btn-palegreen">
                                                Confirm
                                            </button>
                                            <!--Card-->
                                            <button type="submit" id="payment-card" hidden class="btn btn-palegreen">
                                                Confirm
                                            </button>
                                            <!--Bonus coins-->
                                            {% if bonus_c == True %}
                                                <button type="submit" id="payment-bonus-coins" hidden
                                                        class="btn btn-palegreen">Confirm
                                                </button>
                                                <span hidden id="text-id" style="font-size: 15px; color: #70a040">You have enough coins for paying </span>
                                            {% else %}
                                                <button type="button" id="payment-bonus-coins" disabled hidden
                                                        class="btn btn-palegreen">Confirm
                                                </button>
                                                <span hidden id="text-id" style="font-size: 15px; color: red"> You have not enough coins for paying</span>
                                            {% endif %}
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3"><br>
            <div class="card shadow">
                <div class="card-body ">
                    <form class="text-center" style="font-size: 24px">Cart</form>
                    <hr>
                    <table class="table table-stripeds table-bordereds" style="color: #f5eec2 ">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th class="text-center">Quantity</th>
                            <th class="text-center">Price</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for cartitem in context_cart.items.all %}
                            <tr>
                                <th>{{ cartitem.item.title }}</th>
                                <th class="text-center">{{ cartitem.quantity }}</th>
                                <th class="text-center">₴ {{ cartitem.item.price }}</th>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <b>Total Price</b> <span class="float-end">₴ {{ context_cart.get_total }}</span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-2"></div>
{% endblock %}

app/templates/detail-product-info.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block js %}
    <script src="{% static 'js/product-info.js' %}"></script>
{% endblock %}

{% block page %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8"><br>
            <div class="card shadow">
                <div class="card-body">
                    <div class="row">
                        <!-- image col -->
                        <div class="col-md-6">

                            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                                <div class="carousel-inner">
                                    {% thumbnail object.main_image "500x500" crop="center" as im %}
                                        <div class="carousel-item active">
                                            <img src="{{ im.url }}" class="d-block w-100" alt="product_image">
                                        </div>
                                    {% endthumbnail %}
                                    {% for image in object.image_set.all %}
                                        {% thumbnail image.images "500x500" crop="center" as im %}
                                            <div class="carousel-item">
                                                <img src="{{ im.url }}" class="d-block w-100 card-img-top"
                                                     alt="product_img">
                                            </div>
                                        {% endthumbnail %}
                                    {% endfor %}
                                </div>
                                <button class="carousel-control-prev" type="button"
                                        data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Previous</span>
                                </button>
                                <button class="carousel-control-next" type="button"
                                        data-bs-target="#carouselExampleControls" data-bs-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Next</span>
                                </button>
                            </div>


                        </div>
                        <!-- information col -->
                        <div class="col-md-6 text-center">
                            {% csrf_token %}
                            <h1>{{ object.title }}</h1>
                            <hr>
                            <h3>Compound:</h3>
                            <p>{{ object.compound }}</p>
                            <hr>
                            <h3>Description:</h3>
                            <p>{{ object.description }}</p>
                            <hr>
                            <h3>Price:</h3><h4>₴ {{ object.price }}</h4><br>
                            <!-- cart -->
                            <form class="d-grid gap-2" id="button-form" action="{% url 'add_to_cart' %}">
                                <button type="button" id="add-to-cart" class="btn-lg btn-palegreen add-to-cart "
                                        data-item_id="{{ object.id }}">add to cart
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>

{% endblock %}

app/templates/main.html
{% extends 'base.html' %}


{% block page %}
    <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-5 text-center">
        <div style="font-size: 350%; margin-top: 20%; color: #70a040">Welcome to Gros Delivery</div>
        <div style="margin-top: 15%" class="d-grid gap-2 shadow-lg" >
            <a href="/category/" class="btn btn-palegreen btn-lg">Let's start </a>
        </div>
    </div>
    <div class="col-md-3"></div>
    </div>
{% endblock %}

app/templates/order-history.html
{% extends 'base.html' %}
{% load static %}

{% block page %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8"><br>
            <div class="card shadow">
                <div class="card-body">
                    <table class="table table-stripeds table-bordereds text-center" style="color: #f5eec2 ">
                        <thead>
                        <tr>
                            <th>Order ID</th>
                            <th>Products</th>
                            <th>Quantity</th>
                            <th> Order date</th>
                            <th>Total Pay</th>
                            <th>Payment variant</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for order in object_list %}
                                <tr>
                                    <th>{{ order.id }}</th>
                                    <th>
                                        {% for product in order.items.all %}
                                            <p>{{ product.item.title }}</p>
                                        {% endfor %}
                                    </th>
                                    <th>
                                        {% for qty in order.items.all %}
                                            <p>{{ qty.quantity }}</p>
                                        {% endfor %}
                                    </th>
                                    <th>{{ order.ordered_date }}</th>
                                    <th>₴ {{ order.get_total }} </th>
                                    <th>{{ order.payment_choice }}</th>
                                </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

app/templates/room-list.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{% endblock %}

{% block js %}
{% endblock %}

{% block page %}<br>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10" style="color: #39395F">
            {% for room in object_list %}
                <p><a href="/tech-support/{{ room.id }}/" class="btn btn-primary">{{ room }}</a></p>
            {% endfor %}
        </div>
        <div class="col-md-1"></div>
    </div>
{% endblock %}